apiVersion: v1
kind: Pod
metadata:
  name: additional-service
  labels:
    name: additional-service
spec:
  containers:
  - name: additional-service
    image: aaqibjsregistry.azurecr.io/addition-service-docker:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 80
