apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition-service
  template:
    metadata:
      labels:
        app: addition-service
        version: IMAGE_LABEL
    spec:
      containers:
      - name: addition-service
        image: DOCKER_USERNAME/addition-service:IMAGE_LABEL
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: addition-service
spec:
  type: NodePort
  selector:
    app: addition-service
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: addition-service
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: addition-service.K8S_URL
    http:
      paths:
      - backend:
          serviceName: addition-service
          servicePort: 80
        path: /